### PR TITLE
fix nodejs template

### PR DESCRIPTION
**Pull request by tuanng-cognite**
The variable name should be `fetch`.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks!

**Comment by maaland** [comment]
@MikeRalphson could you publish a new version on npm? I need this change. 

Thanks!

**Comment by MikeRalphson** [comment]
Just waiting on another change being tested. If it takes a while I may revert it and publish the other changes.

**Comment by MikeRalphson** [comment]
In the meantime the user-template override option might be useful?

**Pull request merged**
