### PR TITLE
Add Golang template

### PR DESCRIPTION
**Pull request by luigi-riefolo**
Code template for Golang.

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks - please ignore the failing Travis runs, that's nothing to do with your changes.

**Comment by luigi-riefolo** [comment]
@MikeRalphson can we merge it?

**Comment by MikeRalphson** [comment]
I just need to check if adding it to the default languages is going to overflow the right hand column headings, or make them scroll.

**Comment by MikeRalphson** [comment]
LGTM! Many thanks.

**Comment by luigi-riefolo** [comment]
drop a comment here, once https://github.com/Mermade/widdershins/issues/76 is merged, so that I can update the template.

**Pull request merged**
