### PR TITLE
Use httpsnippet to generate code snippets

### PR DESCRIPTION
**Pull request by ceritium**
Allow use [httpsnippet](https://github.com/Mashape/httpsnippet) instead of current template based code generator.
Allow specify which language tabs you wish.

Usage:

```
node ../widdershins/widdershins.js source/swagger.json\
  -o source/doc.md\
  --language_tabs=shell ruby python java php\
  --httpsnippet=true
```

What do you think about this feature?

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Excellent start. I think I would have used httpsnippet if I had known about it! Can we get away without underscore as a dependency? Happy to use ES6 features.

**Comment by MikeRalphson** [comment]
Looking good!

**Comment by ceritium** [comment]
@MikeRalphson I am not so happy with:

```
options.language_tabs = argv.language_tabs.map(function(lang){
  var pair = {};
   pair[lang] = lang;
   return pair;
});
```

What do you think about make `options.language_tabs`  to be just an flat array `['ruby', 'python']`?

In the other hand `httpsnippet` allow specify "target" and "client",  for example:  for "tab shell" could generate code with `curl` or `wget`.

How do you think that we could allow specify that options?

**Comment by MikeRalphson** [comment]
> What do you think about make options.language_tabs to be just an flat array ['ruby', 'python']?

It's done that way as `options.language_tabs` is copied directly to `header.language_tabs` and output in the format Slate (or Shins) expects.

We could split the given array of language tabs at `--` to give us `language--name--client`, or is that too messy?

**Comment by ceritium** [comment]
I like the idea, maybe using `:`  instead of `--`, for example:  

```
--code-tabs=python ruby:Ruby shell:Shell:curl
```

**Comment by ceritium** [comment]
I accept suggestion for var naming :D

**Comment by ceritium** [comment]
@MikeRalphson I hope not to break any feature, I just tested manually these cases:

Works well
```
node widdershins.js swagger.json -o doc.md\
  --language_tabs=shell:Shell-wget:wget ruby:Ruby python java php\
  --httpsnippet=true
```

Problem because slate, show both "shell" at the same time
```
node widdershins.js swagger.json -o doc.md\
  --language_tabs=shell:Shell-wget:wget shell:Shell-curl:curl
  --httpsnippet=true
```

If the template does not exist obviously it does not generate code.
```
node widdershins.js swagger.json -o doc.md\
  --language_tabs=shell:Shell-wget:wget ruby:Ruby python java php\
```

**Comment by MikeRalphson** [comment]
I'm away at the moment with very limited Internet access, so will take a look later this coming week. Thanks again for this.

**Comment by MikeRalphson** [comment]
@ceritium Does this work for you using the the `./specs/petstore.json` file as input? I get

> D:\nodejs\widdershins\node_modules\httpsnippet\src\index.js:46
        throw err
        ^
HARError:

**Comment by ceritium** [comment]
@MikeRalphson `node widdershins.js specs/petstore.json` is working fine for me, I am using yarn and package manager and node 6.10

**Comment by ceritium** [comment]
Yes, Im going to check what is wrong.

**Comment by ceritium** [comment]
Hi!

A lot of time...

This PR need some work before merge and proper tests, I have no time right now and I don't need this feature at the moment, then I prefer close the PR.

If someone wish continue could just fork my work.

**Comment by MikeRalphson** [comment]
Thanks for letting me know @ceritium

**Pull request closed without merging**
