### PR TITLE
access to depth in Shins

### PR DESCRIPTION
**Pull request by lrobledo**
Related to my Shins PR. 
Access to depth allows me to create dynamic tables

### CODE REVIEW

**Comment by MikeRalphson** [comment]
Thanks! Could you remove the changes to package-lock.json as they seem to be unrelated to this change?

**Comment by lrobledo** [comment]
Yes! I'll get that updated

**Comment by lrobledo** [comment]
Okay, that's fixed. Thanks!

**Comment by MikeRalphson** [comment]
Thanks - this actually makes the behaviour agree with the documentation in `templates/openapi3/README.md` so it's a double win. Thanks!

**Pull request merged**
